### ISSUE TITLE
Update to v0.2.0

### ISSUE THREAD

**Issue by unseen-ninja** [asheeeshh/hypurr#1]
Heya, @asheeeshh. With the release of [Version 2](https://github.com/catppuccin/catppuccin/#-palettes=) of the palette and the new flavours we're looking to get ever port updated. Would you be willing to work on this? c:

**Comment by asrvd** [comment]
yes, I talked with @Pocco81 yesterday, I'll start working on both my ports once my exam ends on 25th of june :)

**Comment by unseen-ninja** [comment]
Awesome! Looking forward to this, but for now good luck with the examns. c:
