### ISSUE TITLE
The theme doesn't seem to be working properly.

### ISSUE THREAD

**Issue by BlueFalconHD** [asheeeshh/hypurr#7]
I have a text editor called helix installed, which fills most of the terminal, but the colors/background do not change at all. I have enabled the plugin with `plugins: ['hypurr#latest'],`, but to no avail. I also set `catppuccinTheme: 'mocha'`, but that didn't fix the issue either.
![image](https://user-images.githubusercontent.com/72631767/181971013-a70c6a3f-099c-4370-a0ee-44889f50395b.png)

**Comment by asrvd** [comment]
> I have a text editor called helix installed, which fills most of the terminal, but the colors/background do not change at all. I have enabled the plugin with `plugins: ['hypurr#latest'],`, but to no avail. I also set `catppuccinTheme: 'mocha'`, but that didn't fix the issue either. ![image](https://user-images.githubusercontent.com/72631767/181971013-a70c6a3f-099c-4370-a0ee-44889f50395b.png)

you need to put the `catppuccinTheme: 'mocha'` inside config, you have put it directly inside export, example-
```js
module.exports = {
  config: {
    ...
    catppuccinTheme: 'mocha',
    ...
  },
  ...
  plugins: ['hypurr#latest'],
  ...
}
```

**Comment by BlueFalconHD** [comment]
Oh thank you! I am so stupid!

**Comment by BlueFalconHD** [comment]
Wait actually... nope. Still not working.

**Comment by asrvd** [comment]
> Wait actually... nope. Still not working.

can you share the whole config file
